//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annety
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carts
    {
        public int CartCode { get; set; }
        public int UserCode { get; set; }
        public int ProductKey { get; set; }
        public int Size { get; set; }
        public int Color { get; set; }
        public int Units { get; set; }
    }
}
