//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annety
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartCode { get; set; }
        public Nullable<int> UserCode { get; set; }
        public Nullable<int> ProductKey { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<int> Units { get; set; }
    }
}
