//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annety
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.UsersOrders = new HashSet<UsersOrders>();
            this.WatchList = new HashSet<WatchList>();
        }
    
        public int Code { get; set; }
        [Required(ErrorMessage="Please enter a UserName between 6 to 12 chars")]
       
        [Remote("IsUserExist","Users",HttpMethod="GET", AdditionalFields ="UserName",ErrorMessage ="This USerName is already in use.")]
        public string UserName { get; set; }
        [EmailAddress(ErrorMessage ="Please enter a valid E-mail")]
        [Required(ErrorMessage ="Please enter an Email")]
        [Remote("IsEmailExist","Users",HttpMethod ="GET",AdditionalFields ="Email",ErrorMessage ="This Email is already in use.")]
        public string Email { get; set; }
        [Required(ErrorMessage ="Please enter a password between 6 to 10 chars")]
        public string Password { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersOrders> UsersOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WatchList> WatchList { get; set; }
    }
}
